table DimTerritory
	lineageTag: 0a8a2abd-2bd0-43fe-9a32-d1712cfaede0

	column TerritoryKey
		dataType: string
		lineageTag: 644cd866-c5f6-4b23-b401-82ab38114b77
		summarizeBy: none
		sourceColumn: TerritoryKey

		annotation SummarizationSetBy = Automatic

	column TerritoryName
		dataType: string
		lineageTag: fd064796-f999-47e6-b933-617514c66f4d
		summarizeBy: none
		sourceColumn: TerritoryName

		annotation SummarizationSetBy = Automatic

	column TerritoryRegion
		dataType: string
		lineageTag: 970f157e-0f29-4b39-b3c5-7bf53f7361d7
		summarizeBy: none
		sourceColumn: TerritoryRegion

		annotation SummarizationSetBy = Automatic

	partition DimTerritory = m
		mode: import
		source =
				let
				  Source = raw_SalesFlat,
				  #"Removed other columns" = Table.SelectColumns(Source, {"TerritoryKey", "TerritoryName", "TerritoryRegion"}),
				  #"Removed duplicates" = Table.Distinct(#"Removed other columns", {"TerritoryKey", "TerritoryName", "TerritoryRegion"})
				in
				  #"Removed duplicates"

	annotation PBI_ResultType = Table

