table FactTargets
	lineageTag: d30c2b6e-be5f-4a88-8d33-b110be581e23

	column TargetMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 203235da-feb4-4b9e-b273-cf5ea3ad8d3e
		summarizeBy: none
		sourceColumn: TargetMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TerritoryKey
		dataType: string
		isHidden
		lineageTag: b0bce13d-fdab-43ec-ae9b-a2a0108471cf
		summarizeBy: none
		sourceColumn: TerritoryKey

		annotation SummarizationSetBy = Automatic

	column ProductCategory
		dataType: string
		lineageTag: a8e0e6f8-fb92-4bfb-a57d-08d774a18b4b
		summarizeBy: none
		sourceColumn: ProductCategory

		annotation SummarizationSetBy = Automatic

	column TargetSalesAmount
		dataType: int64
		formatString: 0
		lineageTag: 2dd1c26a-cdb4-453f-892a-040d905d3bdd
		summarizeBy: sum
		sourceColumn: TargetSalesAmount

		annotation SummarizationSetBy = Automatic

	partition FactTargets = m
		mode: import
		source =
				let
				  Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Coding-Forge/PBI-Advanced-Factory/main/data/targets.csv"), [Delimiter = ",", Columns = 4, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"TargetMonth", type date}, {"TerritoryKey", type text}, {"ProductCategory", type text}, {"TargetSalesAmount", Int64.Type}}),
				  #"Filtered rows" = Table.SelectRows(#"Changed column type", each ([TargetMonth] <> null))
				in
				  #"Filtered rows"

	annotation PBI_ResultType = Table

