table FactSales
	lineageTag: ac9aee8c-4460-483d-881f-665d22b45d4a

	column SalesOrderLineKey
		dataType: int64
		formatString: 0
		lineageTag: c3f4623c-901f-4b09-8543-e7d175c8af51
		summarizeBy: count
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 530843d5-0a1d-4375-86a1-0a388e7162a3
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc94ea97-63b2-40ee-a042-934ab6b36075
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column InvoiceDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ffc17c07-391e-4d72-a8f1-141362dfcabb
		summarizeBy: none
		sourceColumn: InvoiceDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerKey
		dataType: string
		isHidden
		lineageTag: bafbd832-b817-4c0c-8ada-4d3a501f82cf
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: string
		isHidden
		lineageTag: cf2949bf-57ff-49be-b8a0-d6366755f8bb
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: string
		isHidden
		lineageTag: 97695d8a-10ee-4e5f-ac24-fc40a63fe80f
		summarizeBy: none
		sourceColumn: TerritoryKey

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 0258ad60-4e53-4ea4-99f7-9a43702c384d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: int64
		formatString: 0
		lineageTag: 182d9887-c230-4db8-84b9-91d22bc16529
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: int64
		formatString: 0
		lineageTag: 0cb2327c-7c1f-4e18-bc17-4bf716fb696b
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	column SalesAmount
		dataType: int64
		formatString: 0
		lineageTag: c11c3fc6-2969-4232-b9c3-3e1da7ed3698
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

	column GrossMargin
		dataType: int64
		formatString: 0
		lineageTag: d39d8cba-78d6-4b2f-b640-68edb4f91f37
		summarizeBy: sum
		sourceColumn: GrossMargin

		annotation SummarizationSetBy = Automatic

	partition FactSales = m
		mode: import
		source =
				let
				  Source = raw_SalesFlat,
				  #"Removed other columns" = Table.SelectColumns(Source, {"SalesOrderLineKey", "OrderDate", "ShipDate", "InvoiceDate", "CustomerKey", "ProductKey", "TerritoryKey", "Quantity", "UnitPrice", "UnitCost", "SalesAmount", "GrossMargin"})
				in
				  #"Removed other columns"

	annotation PBI_ResultType = Table

