table SecurityUserTerritory
	lineageTag: a1b2c3d4-7e8f-4a1b-9c2d-3e4f5a6b7c8d

	column UserPrincipalName
		dataType: string
		lineageTag: b2c3d4e5-8f9a-4b2c-ad3e-4f5a6b7c8d9e
		summarizeBy: none
		sourceColumn: UserPrincipalName

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: c3d4e5f6-9a0b-4c3d-be4f-5a6b7c8d9e0f
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: string
		lineageTag: d4e5f6a7-0b1c-4d4e-cf5a-6b7c8d9e0f1a
		summarizeBy: none
		sourceColumn: TerritoryKey

		annotation SummarizationSetBy = Automatic

	column TerritoryName
		dataType: string
		lineageTag: e5f6a7b8-1c2d-4e5f-da6b-7c8d9e0f1a2b
		summarizeBy: none
		sourceColumn: TerritoryName

		annotation SummarizationSetBy = Automatic

	column AccessLevel
		dataType: string
		lineageTag: f6a7b8c9-2d3e-4f6a-eb7c-8d9e0f1a2b3c
		summarizeBy: none
		sourceColumn: AccessLevel

		annotation SummarizationSetBy = Automatic

	partition SecurityUserTerritory = m
		mode: import
		source =
				let
				  Source = Csv.Document(Web.Contents(RawDataBaseUrl & "security/security-user-territory.csv"), [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				  #"Promoted headers" = Table.PromoteHeaders(#"Changed column type", [PromoteAllScalars = true]),
				  #"Filtered rows" = Table.SelectRows(#"Promoted headers", each ([UserPrincipalName] <> ""))
				in
				  #"Filtered rows"

	annotation PBI_ResultType = Table
