table DimProduct
	lineageTag: d713154e-fc70-4841-918b-8420a2186051

	column ProductKey
		dataType: string
		lineageTag: e3f8fcc4-7ca9-43a4-9890-86d360611efa
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 29cb5ec5-5923-4191-a97a-baf7e902a210
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ProductCategory
		dataType: string
		lineageTag: 2a2badf1-7492-44ca-a98f-537608d10a0d
		summarizeBy: none
		sourceColumn: ProductCategory

		annotation SummarizationSetBy = Automatic

	column ProductSubcategory
		dataType: string
		lineageTag: 7e7352cc-6eaa-4153-aced-41a3b2eab4b0
		summarizeBy: none
		sourceColumn: ProductSubcategory

		annotation SummarizationSetBy = Automatic

	hierarchy 'Product Hierarchy'
		lineageTag: 1a2b3c4d-5e6f-4a1b-8c2d-3e4f5a6b7c8d

		level ProductCategory
			lineageTag: 2b3c4d5e-6f7a-4b2c-9d3e-4f5a6b7c8d9e
			column: ProductCategory

		level ProductSubcategory
			lineageTag: 3c4d5e6f-7a8b-4c3d-ae4f-5a6b7c8d9e0f
			column: ProductSubcategory

		level ProductName
			lineageTag: 4d5e6f7a-8b9c-4d4e-bf5a-6b7c8d9e0f1a
			column: ProductName

	partition DimProduct = m
		mode: import
		source =
				let
				  Source = raw_SalesFlat,
				  #"Removed other columns" = Table.SelectColumns(Source, {"ProductKey", "ProductName", "ProductCategory", "ProductSubcategory"}),
				  #"Removed duplicates" = Table.Distinct(#"Removed other columns", {"ProductKey", "ProductName", "ProductCategory", "ProductSubcategory"})
				in
				  #"Removed duplicates"

	annotation PBI_ResultType = Table

