table DimCustomer
	lineageTag: f118beae-17ea-4d2d-9673-2addd7dd0683

	column CustomerKey
		dataType: string
		lineageTag: 25a8e3ec-72f3-44f5-b50d-08897ae27cd1
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 62957e78-a0a2-4e31-8486-c3847043a511
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column CustomerType
		dataType: string
		lineageTag: 8e9465c1-f96e-420d-baa3-23c0ca976ed3
		summarizeBy: none
		sourceColumn: CustomerType

		annotation SummarizationSetBy = Automatic

	column CustomerState
		dataType: string
		lineageTag: c7a212af-e1be-423d-8540-0f840eabd803
		summarizeBy: none
		sourceColumn: CustomerState

		annotation SummarizationSetBy = Automatic

	column CustomerRegion
		dataType: string
		lineageTag: 297e350c-46e3-44c5-afab-0410be1ef334
		summarizeBy: none
		sourceColumn: CustomerRegion

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				  Source = raw_SalesFlat,
				  #"Removed other columns" = Table.SelectColumns(Source, {"CustomerKey", "CustomerName", "CustomerType", "CustomerState", "CustomerRegion"}),
				  #"Removed duplicates" = Table.Distinct(#"Removed other columns", {"CustomerKey", "CustomerName", "CustomerType", "CustomerState", "CustomerRegion"})
				in
				  #"Removed duplicates"

	changedProperty = Name

	annotation PBI_ResultType = Table

