table product-category-map
	lineageTag: c866b160-24a2-4cc2-9cc1-caaff9e505fe

	column ProductCode
		dataType: string
		lineageTag: 63f443ac-cd1a-4788-b9de-aea860978e12
		summarizeBy: none
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 60973ae9-338c-4128-9ef5-1830814ac278
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ProductCategory
		dataType: string
		lineageTag: 0b55c80e-69c6-4a5a-9a33-3e8ef87dd1fe
		summarizeBy: none
		sourceColumn: ProductCategory

		annotation SummarizationSetBy = Automatic

	column ProductSubcategory
		dataType: string
		lineageTag: 1b2e4ac8-922a-4fa5-9a17-a487365e56b2
		summarizeBy: none
		sourceColumn: ProductSubcategory

		annotation SummarizationSetBy = Automatic

	partition product-category-map = m
		mode: import
		source =
				let
				  Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Coding-Forge/PBI-Advanced-Factory/main/data/reference/product-category-map.csv"), [Delimiter = ",", Columns = 4, QuoteStyle = QuoteStyle.None]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				  #"Promoted headers" = Table.PromoteHeaders(#"Changed column type", [PromoteAllScalars = true]),
				  #"Filtered rows" = Table.SelectRows(#"Promoted headers", each ([ProductCode] <> ""))
				in
				  #"Filtered rows"

	annotation PBI_ResultType = Table

